### ISSUE TITLE
Fix example in readme file

### ISSUE THREAD

**Issue by kariae** [sinlead/drone-kubectl#1]
Hi,

Thanks for the useful plugin, just a quick note, from the `kubectl` file you're already calling the command `kubectl` so no need to have it again in the `commands` list ;)

**Comment by ynilu** [comment]
Hi @kariae,

This plugin just wraps `kubectl` with a bash script.
You still need to call `kubectl` in `commands` to use it.

**Comment by kariae** [comment]
I'm not sure [from source](https://github.com/sinlead/drone-kubectl/blob/c5cb38337851c5a010e1b334d567d5be8b94ec05/kubectl#L14)

**Comment by ynilu** [comment]
I don't see any reason to remove `kubectl` from the README example from that line of code. Can you provide a PoC .drone.yml to show that the `kubectl` in example is not needed?

**Comment by kariae** [comment]
```yaml
- name: deploy-to-server
  image: sinlead/drone-kubectl
  volumes:
    - name: build
      path: /releases
  settings:
    kubernetes_server:
      from_secret: K8S_SERVER
    kubernetes_cert:
      from_secret: K8S_CERT
    kubernetes_token:
      from_secret: K8S_TOKEN
  command:
    - kubectl cp /releases/master*.tar ...
```

and in the logs I had `unknown command "kubectl" for "kubectl"`
