### ISSUE TITLE
Error when using kubectl set image

### ISSUE THREAD

**Issue by mmaryo** [sinlead/drone-kubectl#2]
Hello @ynilu 

I would like to use your plugin to update deployment image version 

I follow your documentation and run commands line

I facing this problem, do you understand why ?

```text
+  kubectl set image deploy/messaging-app  messaging-app=999480714504.dkr.ecr.eu-west-1.amazonaws.com/app:snapshots--dev-a8d890b--5.6.2-SNAPSHOT-messaging-app  -n staging
User "default" set.
Cluster "default" set.
Context "default" created.
Switched to context "default".
Error from server (Forbidden): deployments.extensions "messaging-app" is forbidden: User "system:serviceaccount:staging:default" cannot get resource "deployments" in API group "extensions" in the namespace "staging" 
```

Best

**Comment by ynilu** [comment]
Hi @mmaryo,

It seems like the service account you are using does not have the permission to set image.

You can follow the official guide here to correct it:
https://kubernetes.io/docs/reference/access-authn-authz/authorization/

**Comment by mmaryo** [comment]
Hello 

Now I have a user that can access to API with Token 


```
 kubectl set image deployment messaging-app messaging-app=125480714504.dkr.ecr.eu-west-1.amazonaws.com/monbanquet:snapshots--dev-a8d890b--5.6.2-SNAPSHOT-messaging-app -n staging
User "default" set.
Cluster "default" set.
Context "default" created.
Switched to context "default".
error: the server doesn't have a resource type "deployment" 
```

Is it normal that everything switch to "default" ?

this is my declaration in .drone.yml

```
  - name: Deploy to Kubernates
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server: https://xxx.sk1.eu-west-1.eks.amazonaws.com/api/v1/namespaces
      kubernetes_cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSxxx
      kubernetes_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3xxx
    commands:
      - kubectl set image deployment messaging-app messaging-app=xxx.dkr.ecr.eu-west-1.amazonaws.com/app:snapshots--dev-a8d890b--5.6.2-SNAPSHOT-messaging-app -n staging
```
