### ISSUE TITLE
Have more logs 

### ISSUE THREAD

**Issue by mmaryo** [sinlead/drone-kubectl#3]
Hello 

Is there a way to have more logs ?
Because only one of my builds not works, and all are the same : 

```
+ kubectl set image deployment vor vor=xxx.dkr.ecr.eu-west-1.amazonaws.com/app:snapshots--dev-xxxx-2.0.4-SNAPSHOT-vor -n default
User "default" set.
Cluster "default" set.
Context "default" created.
Switched to context "default".
Error from server (Forbidden): deployments.extensions "vor" is forbidden: User "system:serviceaccount:default:drone-service-account" cannot get resource "deployments" in API group "extensions" in the namespace "default" 
```

```
  - name: Deploy to Kubernates
    image: sinlead/drone-kubectl
    commands:
      - kubectl set image deployment vor vor=12548071xxx.ecr.eu-west-1.amazonaws.com/app:snapshots--dev-xxxx-2.0.4-SNAPSHOT-vor -n default
    settings:
      kubernetes_server: https://xxxx.eu-west-1.eks.amazonaws.com
      kubernetes_cert: LS0tLS1CRUdJTiBDRVJUSXXXXXXX
      kubernetes_token: eyJhbGciOiJSUzI1NiIsImtpZXXXXXX
```
